### ISSUE TITLE
TypeError: Object #<Object> has no method 'methods'

### ISSUE THREAD

**Issue by alexfu** [MiroHibler/meteor-mailchimp#26]
I'm not sure if this is an issue with this library or meteor, but when install this and run `meteor`, I get the following...

```
TypeError: Object #<Object> has no method 'methods'
  at Package (packages/miro:mailchimp/lib/server/mailchimp.js:57:1)
  at /path/to/project/.meteor/local/build/programs/server/packages/miro_mailchimp.js:105:4
  at /path/to/project/.meteor/local/build/programs/server/packages/miro_mailchimp.js:114:3
  at /path/to/project/.meteor/local/build/programs/server/boot.js:222:10
```

**Comment by alexfu** [comment]
Fixed it by removing `standard-app-packages`
